// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "HTML Editor",
    platforms: [
        .iOS("15.2"),
        .macOS("11.0")
    ],
    products: [
        .iOSApplication(
            name: "HTML Editor",
            targets: ["AppModule"],
            displayVersion: "0.1.1",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .paper),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite),
                .outgoingNetworkConnections()
            ],
            appCategory: .developerTools
        )
    ],
    dependencies: [
        .package(url: "https://github.com/siteline/SwiftUI-Introspect.git", "0.1.4"..<"1.0.0"),
        .package(url: "https://github.com/dropbox/SwiftyDropbox.git", "9.1.0"..<"10.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Introspect", package: "SwiftUI-Introspect"),
                .product(name: "SwiftyDropbox", package: "SwiftyDropbox")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
